name: Build and test ytcc

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install system dependencies
      run: |
        sudo apt-get install -y gettext ffmpeg
        sudo ln -s /bin/true /bin/mpv
    - name: Setup ytcc and Python dependencies
      run: |
        python setup.py install
    - name: Type check with MyPy
      run: |
        python -m pip install --upgrade pip
        pip install mypy sqlalchemy-stubs
        mypy ytcc
    - name: Check docstyle with pydocstyle
      run: |
        pip install pydocstyle
        pydocstyle
    - name: Linting with pylint
      run: |
        pip install pylint
        pylint ytcc
    - name: Run tests with nose
      run: |
        pip install nose
        nosetests
